### ISSUE TITLE
bug: getParentGlue

### ISSUE THREAD

**Issue by f1yegor** [42wim/dt#2]
installed now
```go get github.com/42wim/dt```
```
dt yandex.ru                                                                                                                                           NS             |IP              |LOC |ASN     |ISP        |rtt         |Serial     |DNSSEC   |ValidFrom |ValidUntil
ns2.yandex.ru. |93.158.134.1    |RU  |AS13238 |YANDEX, RU |32.958385ms |2017050606 |disabled |          |
ns2.yandex.ru. |2a02:6b8:0:1::1 |RU  |AS13238 |YANDEX, RU |error       |error      |error    |
ns1.yandex.ru. |213.180.193.1   |RU  |AS13238 |YANDEX, RU |31.533485ms |2017050606 |invalid  |a long while ago |a long while ago
ns1.yandex.ru. |2a02:6b8::1     |RU  |AS13238 |YANDEX, RU |error       |error      |error    |
panic: runtime error: index out of range

goroutine 1 [running]:
main.getParentGlue(0x7ffee887b434, 0x9, 0xd, 0xc4200c39a0, 0x2, 0x2, 0x0)
        /home/f1/media/data/projects/gorepo/src/github.com/42wim/dt/glue.go:93 +0x3f0
main.(*Glue).CheckParent(0xc42005fd30, 0x7ffee887b434, 0x9, 0xc420160240, 0xc420168000, 0x40, 0x0, 0x0, 0x0)
        /home/f1/media/data/projects/gorepo/src/github.com/42wim/dt/glue.go:16 +0x39
main.(*Glue).CreateReport(0xc42005fd30, 0x7ffee887b434, 0x9)
        /home/f1/media/data/projects/gorepo/src/github.com/42wim/dt/glue.go:38 +0xb7
main.main()
        /home/f1/media/data/projects/gorepo/src/github.com/42wim/dt/main.go:239 +0x70f
```

**Comment by 42wim** [comment]
Thanks for reporting! 
Error handling needs improvement. 
Could you do a ```go get -u github.com/42wim/dt``` and see if it's fixed for you ?

**Comment by f1yegor** [comment]
It's always good to check errors) Fixed. Thanks for quick fix.
